export const landing = {
  cta: "დაჯავშნე საცდელი გაკვეთილი",
  ctaShort: "საცდელი გაკვეთილი",
  giftLine: "პირველი 2 გაკვეთილი — საჩუქრად",
  login: "შესვლა",
  loginCabinet: "შესვლა კაბინეტში",
  nav: [
    { href: "#nina", id: "nina", label: "ნინა" },
    { href: "#metodo", id: "metodo", label: "მეთოდი" },
    { href: "#istorias", id: "istorias", label: "სიუჟეტები" },
    { href: "#materiales", id: "materiales", label: "მასალები" },
    { href: "#precio", id: "precio", label: "ფასი" },
    { href: "#preguntas", id: "preguntas", label: "კითხვები" },
  ],
  hero: {
    kicker: "¡Hola!",
    note: "soy Nina",
    name: "Nina",
    titleBefore: "Tu Profe de ",
    titleAccent: "Español",
    ariaLabel: "Nina – Tu Profe de Español",
    quote: "ესპანურ ენას კი არ ვასწავლი, ვასწავლი ესპანურ სამყაროს",
    descriptor: "ინდივიდუალური ონლაინ გაკვეთილები ნულიდან — ზრდასრულებისთვის, ნაბიჯ-ნაბიჯ, Poco a Poco.",
    chips: ["ნულიდან", "ინდივიდუალური", "ონლაინ", "75 წუთი"],
    methodLink: "როგორ მიმდინარეობს გაკვეთილი ↓",
    imageAlt: "ნინა დგას და გიღიმის, ხელში ყავა უჭირავს",
    mobileAlt: "ნინა ქვის მოაჯირზე ზის და ესპანური ქალაქის ხედს უყურებს",
  },
  meet: {
    kicker: "Conóceme",
    title: "გამარჯობა, მე ნინა ვარ",
    paragraphs: [
      "მთელი ცხოვრება ენებს ვსწავლობ. ქართულის გარდა ვისწავლე გერმანული, რუსული, ინგლისური, ესპანური და იტალიური.",
      "ყოველთვის მინდოდა, რომ ჩემი სწავლა ყოფილიყო საინტერესო, მხიარული, მრავალფეროვანი და ჩემს მიზნებზე მორგებული. ზუსტად ასეთ გაკვეთილებს ვქმნი ჩემი მოსწავლეებისთვის.",
    ],
    stamps: [
      { kicker: "Hallo", label: "გერმანული", short: "გერ." },
      { kicker: "Привет", label: "რუსული", short: "რუს." },
      { kicker: "Hello", label: "ინგლისური", short: "ინგ." },
      { kicker: "¡Hola!", label: "ესპანური", short: "ესპ.", highlighted: true },
      { kicker: "Ciao", label: "იტალიური", short: "იტა." },
    ],
    closing: "Un día a la vez.",
    imageAlt: "ნინას სამუშაო ოთახი: მაგიდა, რვეული და თბილი სინათლე",
  },
  why: {
    kicker: "¿Por qué conmigo?",
    title: "რატომ ნინასთან",
    aside: "ეს არ არის ენის სკოლა. ეს ნინას ესპანური სამყაროა — და შენ მისი ნაწილი ხდები.",
    cards: [
      { number: "01", title: "ესპანური ნულიდან", text: "წინასწარი ცოდნა არ გჭირდება. ვიწყებთ პირველი „¡Hola!“-დან.", image: "/illustrations/spots/spot-standing.webp", tint: "bg-teal-soft" },
      { number: "02", title: "სიუჟეტები და არა წესები", text: "ენას სიტუაციებსა და პერსონაჟებში ხვდები — წესი მერე თავად ჩნდება.", image: "/illustrations/spots/spot-notebook.webp", tint: "bg-mustard-soft" },
      { number: "03", title: "შენზე მორგებული", text: "ტემპი და ლექსიკა შენი მიზნით: მოგზაურობა, სწავლა თუ გადასვლა.", image: "/illustrations/spots/spot-map.webp", tint: "bg-burgundy-soft" },
      { number: "04", title: "ლამაზი მასალები", text: "ბარათები, დიალოგები და ვიდეოები — სპეციალურად ამ კურსისთვის.", image: "/illustrations/spots/spot-coffee.webp", tint: "bg-sage-soft" },
      { number: "05", title: "შენი კაბინეტი", text: "ყველა გაკვეთილი და მასალა ერთ პირად სივრცეში.", image: "/illustrations/spots/spot-phone.webp", tint: "bg-sand-soft" },
      { number: "06", title: "Poco a Poco", text: "ნაბიჯ-ნაბიჯ — ყოველი ახალი „აგური“ წინაზე დგას. მყარი საფუძველი — თავიდანვე.", image: "/illustrations/spots/spot-walking.webp", tint: "bg-navy", inverted: true },
    ],
  },
  stories: {
    kicker: "Nuestras historias",
    title: "ესპანური, რომელიც ისტორიასთან ერთად იზრდება",
    text: "ესენი არიან ლაურა, ანა და ლუკასი. გაკვეთილიდან გაკვეთილზე ისევ შეხვდები მათ — კაფეში, ქუჩაში, სამსახურში. შენი ესპანური მათ ისტორიასთან ერთად იზრდება.",
    imageAlt: "ოთხი მეგობარი კაფეში, ესპანურ ქალაქში",
    names: [
      { name: "Laura", tone: "text-on-dark" },
      { name: "Nina", tone: "text-mustard" },
      { name: "Ana", tone: "text-burgundy" },
      { name: "Lucas", tone: "text-on-dark" },
    ],
    people: [
      { name: "Ana", text: "ქართველი ვებ-დიზაინერი ბარსელონაში" },
      { name: "Nina", text: "შენი პროფე — ყოველთვის გვერდით" },
      { name: "Laura", text: "ვალენსიაში ცხოვრობს და ქალაქს გიჩვენებს" },
      { name: "Lucas", text: "ანას მეგობარი — კაფეში ყავას უკვეთავს" },
    ],
    dialogueLabel: "DIÁLOGO",
    dialoguePlace: "En el café",
    englishToggle: "EN",
    lines: [
      { who: "Ana", initial: "A", tone: "bg-burgundy-soft text-burgundy", es: "¡Hola! ¿Qué tal? Soy Ana.", en: "Hi! How are you? I'm Ana." },
      { who: "Lucas", initial: "L", tone: "bg-teal-soft text-teal-deep", es: "¡Hola, Ana! Yo soy Lucas. ¿De dónde eres?", en: "Hi, Ana! I'm Lucas. Where are you from?" },
      { who: "Ana", initial: "A", tone: "bg-burgundy-soft text-burgundy", es: "Soy de Georgia, pero vivo en Barcelona.", en: "I'm from Georgia, but I live in Barcelona." },
      { who: "Lucas", initial: "L", tone: "bg-teal-soft text-teal-deep", es: "¡Qué bien! ¿Tomamos un café?", en: "How nice! Shall we grab a coffee?" },
    ],
    danceTitle: "დააჭირე და იცეკვე",
    moves: [
      { id: "left", label: "← izquierda", word: "¡izquierda!", dx: -1, dy: 0 },
      { id: "right", label: "derecha →", word: "¡derecha!", dx: 1, dy: 0 },
      { id: "up", label: "↑ arriba", word: "¡arriba!", dx: 0, dy: -1 },
      { id: "down", label: "↓ abajo", word: "¡abajo!", dx: 0, dy: 1 },
    ],
  },
  method: {
    kicker: "Paso a paso",
    title: "როგორ მიმდინარეობს გაკვეთილი",
    text: "ჯერ სიტუაცია, მერე წესი. ასე ენა ბუნებრივად „ჯდება“.",
    steps: [
      { step: "1 · Mira", title: "ხედავ სიტუაციას", text: "ვიდეო-დიალოგი, სადაც ესპანური ცოცხლად ჟღერს.", icon: "video" as const },
      { step: "2 · Observa", title: "ამჩნევ კანონზომიერებას", text: "თავად პოულობ, რა მეორდება და როგორ იცვლება.", icon: "search" as const },
      { step: "3 · Entiende", title: "იგებ წესს", text: "მოკლე, ვიზუალური ახსნა — როცა უკვე გესმის, რატომ.", icon: "grammar" as const },
      { step: "4 · Habla", title: "იყენებ", text: "ლაპარაკობ, თამაშობ, აწყობ საკუთარ დიალოგებს.", icon: "dialogue" as const },
    ],
    rulesKicker: "Mis reglas",
    rulesTitle: "ნინას ოთხი წესი",
    rulesText: "ჩვენი საკლასო ოთახის — თუნდაც ონლაინ — წესები.",
    rules: [
      { title: "¡Nos divertimos!", lead: "ვერთობით", text: "სერიოზული სწავლა სიამოვნების გარეშე არ გამოდის." },
      { title: "Con calma", lead: "ვსწავლობთ საფუძვლიანად", text: "კომფორტულ ტემპში, მყარ საფუძველზე." },
      { title: "¡Viva el error!", lead: "გვიყვარს შეცდომები", text: "თქვი, რაც თავში მოგივა — შეცდომა გვიჩვენებს, სად ვიმუშაოთ." },
      { title: "¡Desde el día uno!", lead: "ესპანურად პირველივე გაკვეთილიდან", text: "ვლაპარაკობ და ვთარგმნი — ყური ნელ-ნელა ეჩვევა." },
    ],
  },
  materials: {
    kicker: "Materiales",
    title: "მასალები, რომლებიც ამ კურსისთვის იქმნება",
    text: "ყველა ბარათი, დიალოგი და სავარჯიშო ნინას სამყაროს ნაწილია — და ყოველ მოსწავლეს თავისი ტემპითა და მიზნით ერგება.",
    chips: ["ბარათები", "ლექსიკა", "დიალოგები", "აუდიო", "ვიდეო", "სავარჯიშოები", "გამოთქმა"],
    footnote: "hecho con cariño, para ti",
    cardKicker: "TEMA 1",
    cardTitle: "Los saludos",
    greetings: [
      ["¡Hola!", "გამარჯობა"],
      ["Buenos días", "დილა მშვიდობისა"],
      ["Buenas tardes", "შუადღე მშვ."],
      ["Buenas noches", "ღამე მშვ."],
      ["¡Adiós!", "ნახვამდის"],
    ],
    vocabTitle: "En el café",
    vocabKicker: "VOCABULARIO",
    vocab: [
      ["el café", "ყავა"],
      ["la tostada", "ტოსტი"],
      ["la cuenta", "ანგარიში"],
      ["el vaso de agua", "ჭიქა წყალი"],
    ],
    audioTitle: "Diálogo 3",
    audioMeta: "En el café · 1:24",
    sounds: ["ll", "ñ", "j", "rr", "ce", "gu"],
    miniDialogue: [
      ["Ana", "¿Me pones un café, por favor?"],
      ["Lucas", "¡Claro! ¿Con leche?"],
      ["Ana", "Sí, gracias."],
    ],
    exerciseKicker: "EJERCICIO · 3 / 8",
    exerciseTitle: "ააწყე წინადადება",
    tiles: ["Soy", "de", "Georgia", "pero", "vivo", "en", "Barcelona"],
    check: "შემოწმება",
  },
  cabinet: {
    kicker: "Tu espacio",
    title: "შენი პირადი კაბინეტი",
    text: "გაკვეთილის შემდეგ ყველაფერი შენთან რჩება — გადახედე, გაიმეორე, გააგრძელე.",
    checks: ["ყველა გაკვეთილი ერთ ადგილას", "თითოეული გაკვეთილის მასალები", "ხედავ, რა დაასრულე და რა გელოდება"],
    imageAlt: "ტერასის მაგიდა რვეულით და ყავით",
    hello: "¡Hola, Mariam!",
    continueLabel: "გაკვეთილი 6 · En el café",
    homework: "საშინაო დავალება",
    fromNina: "ნინასგან",
  },
  path: {
    kicker: "Poco a Poco",
    title: "შენი გზა — ნულიდან თავდაჯერებულ A1-მდე",
    text: "ნაბიჯ-ნაბიჯ, შენს ტემპში. ყოველი გაჩერება წინაზე დგას.",
    aria: "კურსის გზა: მისალმება, თავის გაცნობა, კაფეში, მიმართულებები, ჩემი დღე, ოჯახი, საყიდლები, A1 შემოწმება",
    draft: "ბლოკების სახელები სამუშაოა — საბოლოო სია ნინასთან დაზუსტდება.",
    stops: [
      { es: "¡Hola!", ka: "მისალმება", state: "done" },
      { es: "Me presento", ka: "თავის გაცნობა", state: "done" },
      { es: "En el café", ka: "კაფეში", state: "done" },
      { es: "¿Dónde está?", ka: "მიმართულებები", state: "next" },
      { es: "Mi día", ka: "ჩემი დღე", state: "next" },
      { es: "Mi familia", ka: "ოჯახი", state: "next" },
      { es: "De compras", ka: "საყიდლები", state: "next" },
      { es: "¡A1!", ka: "შემოწმება", state: "goal" },
    ],
  },
  gift: {
    kicker: "Un regalo para ti",
    title: "პირველი 2 გაკვეთილი — საჩუქრად",
    text: "ორი გაკვეთილი, რომ ერთმანეთი გავიცნოთ და ესპანური უკვე იგრძნო — სანამ რამეს გადაიხდი.",
    checks: ["ვეცნობით ერთმანეთს", "ვარკვევთ შენს მიზნებსა და ტემპს", "პირველი ვიდეო-დიალოგები", "პირველი ბარათები", "ერთად ვაწყობთ პირველ დიალოგებს"],
    imageAlt: "ნინა ქვის მოაჯირზე ზის და ესპანური ქალაქის ხედს უყურებს",
    walkingAlt: "ნინა მიდის ესპანურ ქუჩაში",
  },
  pricing: {
    kicker: "Precio",
    title: "მარტივად: ერთი გაკვეთილი, ყველაფერი შიგნით",
    text: "არანაირი რთული პაკეტი. იხდი გაკვეთილს — მასალები, კაბინეტი და შენი გეგმა უკვე მასშია.",
    name: "ინდივიდუალური გაკვეთილი",
    per: "/ გაკვეთილი",
    online: "ონლაინ",
    oneToOne: "1 : 1",
    includes: ["პერსონალური მასალები", "პირადი ონლაინ კაბინეტი", "ინდივიდუალური გეგმა შენი მიზნით"],
    note: "ფასიანი გაკვეთილები მესამედან იწყება.",
  },
  faq: {
    kicker: "¿Preguntas?",
    title: "ხშირად დასმული კითხვები",
    text: "ვერ იპოვე პასუხი? მომწერე — სიამოვნებით გიპასუხებ.",
    items: [
      { id: "zero", question: "ესპანური საერთოდ არ ვიცი. შეიძლება?", answer: "რა თქმა უნდა. კურსი ზუსტად ნულიდან იწყება — პირველი სიტყვიდან, პირველი „¡Hola!“-დან. წინასწარი ცოდნა საჭირო არ არის." },
      { id: "how", question: "როგორ ტარდება გაკვეთილები?", answer: "ონლაინ, ინდივიდუალურად, 75 წუთი. ვუყურებთ ვიდეო-დიალოგებს, ვმუშაობთ ბარათებზე და ბევრს ვლაპარაკობთ. ბმულს გაკვეთილამდე გამოგიგზავნი." },
      { id: "often", question: "რამდენად ხშირად უნდა ვისწავლო?", answer: "ამას პირველ საუბარზე ერთად ვწყვეტთ — შენი დროისა და მიზნის მიხედვით." },
      { id: "cabinet", question: "რა არის კაბინეტში?", answer: "შენი გაკვეთილები და თითოეულის მასალები: ბარათები, დიალოგები, აუდიო, ვიდეო, სავარჯიშოები და საშინაო დავალება — ერთ ადგილას." },
      { id: "goal", question: "შემიძლია ვისწავლო მოგზაურობისთვის, გადასასვლელად ან სწავლისთვის?", answer: "დიახ. თემებსა და ლექსიკას შენს მიზანს ვუსადაგებ — იქნება ეს მოგზაურობა, საცხოვრებლად გადასვლა თუ სწავლა." },
      { id: "gift", question: "როგორ მუშაობს 2 საჩუქარი გაკვეთილი?", answer: "პირველი ორი გაკვეთილი უფასოა: ვეცნობით ერთმანეთს, ვადგენთ ტემპს და უკვე ვიწყებთ ესპანურს. ფასიანი გაკვეთილები მესამედან იწყება." },
      { id: "pay", question: "როგორ ვიხდი?", answer: "გადახდის წესს პირველ საუბარზე შევთანხმდებით." },
      { id: "miss", question: "რა მოხდება, თუ გაკვეთილს გამოვტოვებ?", answer: "თუ ვერ მოხვალ, წინასწარ მომწერე და გაკვეთილს გადავიტანთ." },
    ],
  },
  final: {
    kicker: "¡Vamos!",
    title: "მოდი, ესპანური ერთად ვისწავლოთ",
    imageAlt: "ნინა ფეხმორთხმით ზის ყავით ხელში და იღიმება",
  },
  footer: {
    site: "საიტი",
    contact: "კონტაქტი",
    social: "სოციალური",
    students: "მოსწავლეებისთვის",
    email: "ელ-ფოსტა",
    phone: "ტელეფონი",
    telegram: "Telegram",
    instagram: "Instagram",
    facebook: "Facebook",
    tiktok: "TikTok",
    signature: "Nina - Tu Profe De Español",
    rights: "© 2026 · ყველა უფლება დაცულია",
    privacy: "კონფიდენციალურობა",
    terms: "წესები",
  },
  menuNote: "Un día a la vez",
  menuLabel: "მენიუ",
  close: "დახურვა",
  booking: {
    hello: "¡Hola!",
    aside: "შეავსე ფორმა და ნინა თავად დაგიკავშირდება, რომ შეთანხმდეთ დროზე.",
    name: "სახელი",
    phone: "ტელეფონი",
    email: "ელ-ფოსტა",
    optional: "(არასავალდებულო)",
    channel: "როგორ დაგიკავშირდე?",
    goal: "რისთვის გინდა ესპანური?",
    days: "სასურველი დღეები",
    time: "დღის მონაკვეთი",
    note: "შენიშვნა",
    consent: "ვეთანხმები, რომ ნინამ ჩემი მონაცემები გამოიყენოს დასაკავშირებლად",
    submit: "გაგზავნა",
    sending: "იგზავნება…",
    summary: "გთხოვ, შეავსე მონიშნული ველები.",
    nameError: "შეიყვანე სახელი",
    phoneError: "ნომერი არასრულია",
    emailError: "ელ-ფოსტა სავალდებულოა",
    consentError: "თანხმობა სავალდებულოა",
    sendError: "ვერ გაიგზავნა. სცადე თავიდან.",
    thanks: "¡Gracias!",
    success: "მადლობა! ნინა მალე დაგიკავშირდება",
    soon: "¡Hasta pronto!",
    back: "დაბრუნება საიტზე",
    channels: [
      { id: "PHONE", label: "ტელეფონი" },
      { id: "WHATSAPP", label: "WhatsApp" },
      { id: "TELEGRAM", label: "Telegram" },
      { id: "EMAIL", label: "ელ-ფოსტა" },
    ],
    goals: [
      { id: "TRAVEL", label: "მოგზაურობა" },
      { id: "STUDY", label: "სწავლა" },
      { id: "RELOCATION", label: "გადასვლა" },
      { id: "FUN", label: "გართობისთვის" },
      { id: "OTHER", label: "სხვა" },
    ],
    week: [
      { id: "MON", label: "ორშ" },
      { id: "TUE", label: "სამ" },
      { id: "WED", label: "ოთხ" },
      { id: "THU", label: "ხუთ" },
      { id: "FRI", label: "პარ" },
      { id: "SAT", label: "შაბ" },
      { id: "SUN", label: "კვ" },
    ],
    times: [
      { id: "MORNING", label: "დილა" },
      { id: "DAY", label: "დღე" },
      { id: "EVENING", label: "საღამო" },
    ],
  },
} as const;

export function assertLandingReady() {
  if (process.env.NODE_ENV !== "production" || process.env.ALLOW_PLACEHOLDER_COPY === "true") return;
  if (hasPlaceholder(landing)) {
    throw new Error("landing.ka.ts still contains draft placeholders");
  }
}

function hasPlaceholder(value: unknown): boolean {
  if (typeof value === "string") return /\[[^[\]]+\]/.test(value);
  if (Array.isArray(value)) return value.some(hasPlaceholder);
  if (value && typeof value === "object") return Object.values(value).some(hasPlaceholder);
  return false;
}
